cart_pole:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  cart_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: cart_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

